spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/employee?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.abyss.pojo
  mapper-locations: classpath:com.abyss.mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
